# Header
menu:
  主页: /
  所有文章: /archives
  unix: /categories/unix
  web: /categories/web

# SubNav
subnav:
  github: "https://github.com/maxming2333"
  weibo: "http://weibo.com/578511458/home"
  rss: "#"
  zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: 'UA-79036705-1'
favicon: /favicon.png

#你的头像url
avatar: "https://avatars2.githubusercontent.com/u/8816730?v=3&s=460"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends: false

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 会写代码滴水泥佬~